### ISSUE TITLE
Want to add some more most useful algorithms

### ISSUE THREAD

**Issue by Vaishu03** [Einsteinia11/Data-Structures-and-Algorithm-with-Design-and-Analysis#10]
1) DFS
2) BFS
3) KMP
4) Floyd's Cycle Detection Algorithm

Please consider this under Hacktoberfest 2023 and I would like to work on this issue..

**Comment by Einsteinia11** [comment]
Yes you can start working on...

**Comment by Vaishu03** [comment]
Sure!
