### ISSUE TITLE
want to add more algorithms and data structures

### ISSUE THREAD

**Issue by SmashSidak-1508** [Einsteinia11/Data-Structures-and-Algorithm-with-Design-and-Analysis#11]
I will add the trie data structure algorithms- like insert, search and delete
Skip List Algorithms:
Search, Insertion, Deletion: Operations in a data structure similar to a linked list with multiple layers for efficient searching

and few string matching algorithms

**Comment by SmashSidak-1508** [comment]
kindly assign me this issue

**Comment by Gyanthakur** [comment]
Requesting additional algorithms and data structures topics. Assign to me, eager to contribute and enhance the repository.

**Comment by Einsteinia11** [comment]
Hey!
yes you can start working on it @SmashSidak-1508

**Comment by Einsteinia11** [comment]
Hey @Gyanthakur !
You can create a new issue and let me know about the algorithms you would like to work on. If you are not sure about what topics you should work on so you can create a new folder DSA Practice Questions in which you can add problems from Leetcode and their solutions related to DSA
