### ISSUE TITLE
DSA folder for important interview questions

### ISSUE THREAD

**Issue by SmashSidak-1508** [Einsteinia11/Data-Structures-and-Algorithm-with-Design-and-Analysis#21]
kindly assign me this issue. I will contribute to this issue. and will add few more algorithms there

**Comment by SmashSidak-1508** [comment]
will add solutions for leetcode questions in this folder @Einsteinia11

**Comment by Einsteinia11** [comment]
ohk make sure to add the question in comment then provide the solution code to it
