### ISSUE TITLE
I want to add sorting algorithm's in python.

### ISSUE THREAD

**Issue by anish2105** [Einsteinia11/Data-Structures-and-Algorithm-with-Design-and-Analysis#24]
I want to add  insertion sort , bubble sort, selection sort, quick sort and merge sort in python. So please assign me under hackoberfest.

**Comment by Einsteinia11** [comment]
Hey,
yes assigning to you, you can start working on 
Happy coding :)

**Comment by anish2105** [comment]
@Einsteinia11 Hey i have added the files , check it and merge it
