### ISSUE TITLE
I want to add some most frequently useful algorithms codes

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [Einsteinia11/Data-Structures-and-Algorithm-with-Design-and-Analysis#4]
1)K-way merge Algorithm

2)Stack Reduced Quick Sort

3)Merge sort combined with Insertion Sort

4)Prims, Topological, Kruskal's algorithm

5)DijKstra , Floyd Warshall ,bellman ford algorithm

6)Backtracking
a) Rat Maze
b) N-Queen
c) Sudoku
d) Sum of Subset

7) Activity selection , Huffman Encoding .

Please consider this under Hacktoberfest_2023 , I am interested to Contribute my self : )

**Comment by Einsteinia11** [comment]
Ohkay you can start working on it, once received your pull request will assign you hacktoberfest-accepted label 
Happy coding!✨

**Comment by Bharath-KumarReddy** [comment]
Ok sure : )

**Comment by Bharath-KumarReddy** [comment]
I had resolved this issue and 
I had made a PR #6

Once please check and add a label hacktoberfest_23 : )

Kindly inform incase of further modifications : )
