### ISSUE TITLE
Want to update README.md file

### ISSUE THREAD

**Issue by SmashSidak-1508** [Einsteinia11/Data-Structures-and-Algorithm-with-Design-and-Analysis#47]
want to update how DSA is useful in real life and examples of each data structure how it is useful to solve the real life problem solving will add reference for each topic witht their applications

**Comment by Einsteinia11** [comment]
Hey,
yes you can start working on it.

**Comment by SmashSidak-1508** [comment]
assign me the issue @Einsteinia11
