### ISSUE TITLE
Want to add Dutch National Flag Algorithm and Rotate array Problem

### ISSUE THREAD

**Issue by Vaishu03** [Einsteinia11/Data-Structures-and-Algorithm-with-Design-and-Analysis#59]
Hey @Einsteinia11 I would like to add some more important algorithms like Dutch National Flag Algorithm and Rotate array problem to this repo.
Can you assign this task to me under hacktoberfest2023...

**Comment by Einsteinia11** [comment]
hey,
yes you can start working on it
happy coding :)
