### ISSUE TITLE
Adding greedy and dynamic programming algorithms 

### ISSUE THREAD

**Issue by dotsbeauty** [Einsteinia11/Data-Structures-and-Algorithm-with-Design-and-Analysis#8]
Hi there, 
Few algorithms like Prims, Knapsack, dijkstra, 0/1 Knapsack, Flyod Warshell, etc can be added.
Please assign this to me.

**Comment by Einsteinia11** [comment]
Hey, 
Yes you can start working on it, make sure they are not already present in the repo.
